exec:
  filename: generated/exec.go
model:
  filename: models/generated.go

autobind:
  - github.com/qhenkart/gqlgen/example/starwars/models

models:
  ReviewInput:
    model: github.com/qhenkart/gqlgen/example/starwars/models.Review
  Starship:
    fields:
      length:
        resolver: true
