exec:
  filename: generated/exec.go
model:
  filename: models/generated.go

models:
  Droid:
    model: github.com/qhenkart/gqlgen/example/starwars/models.Droid
  FriendsConnection:
    model: github.com/qhenkart/gqlgen/example/starwars/models.FriendsConnection
  Human:
    model: github.com/qhenkart/gqlgen/example/starwars/models.Human
  Review:
    model: github.com/qhenkart/gqlgen/example/starwars/models.Review
  ReviewInput:
    model: github.com/qhenkart/gqlgen/example/starwars/models.Review
  Starship:
    fields:
      length:
        resolver: true
